name: fx_rx
description: Tiny reactive state management for Flutter with zero boilerplate.
version: 0.0.1
homepage: https://example.com
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
